import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider, RecoilProvider } from "@/components/providers";
import { InitialWeatherManager } from "@/components/common";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<RecoilProvider>
					<ReactQueryProvider>
						<InitialWeatherManager />
						{children}
					</ReactQueryProvider>
				</RecoilProvider>
			</body>
		</html>
	);
}
